# Generated by Django 4.0.3 on 2022-04-10 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userconfig', '0002_network_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_on', models.DateTimeField(auto_now_add=True)),
                ('recording_length', models.IntegerField(blank=True, null=True)),
                ('camera_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userconfig.camera')),
            ],
        ),
    ]
