# Generated by Django 4.0.3 on 2022-04-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='file_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='file_path',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
