# Generated by Django 4.0.3 on 2022-04-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_camera_id_recording_cameraid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='recordedOn',
        ),
    ]
